# ============================================================================
# Docker Compose Override for Native Worker
# ============================================================================
# Use this when running the processing worker natively on macOS for Metal/MPS.
#
# Usage:
#   docker-compose -f docker-compose.yml -f docker-compose.native-worker.yml up -d
#
# This configuration:
# - Scales processing-worker to 0 (disabled)
# - Keeps ChromaDB and Copyparty running in Docker
# - Expects worker to run natively on host at http://host.docker.internal:8002
# ============================================================================

services:
  # Scale worker to 0 to disable it (but keep service definition)
  processing-worker:
    deploy:
      replicas: 0

  # Update Copyparty to connect to native worker on host
  copyparty:
    environment:
      # Point to native worker on host
      - WORKER_HOST=host.docker.internal  # macOS Docker Desktop hostname
      - WORKER_PORT=8002
    extra_hosts:
      # Allow container to reach host
      - "host.docker.internal:host-gateway"

  # ChromaDB - ensure accessible from both copyparty and native worker
  chromadb:
    ports:
      - "8001:8000"  # Accessible from host for native worker
