# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import embedding_pb2 as embedding__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in embedding_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EmbeddingServiceStub(object):
    """EmbeddingService provides multi-vector embedding operations.
    Supports both text and image inputs via ColNomic multimodal embeddings.
    Text and image embeddings share the same vector space.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EncodeDocuments = channel.unary_unary(
                '/shikomi.embedding.v1.EmbeddingService/EncodeDocuments',
                request_serializer=embedding__pb2.EncodeRequest.SerializeToString,
                response_deserializer=embedding__pb2.EncodeResponse.FromString,
                _registered_method=True)
        self.EncodeQueries = channel.unary_unary(
                '/shikomi.embedding.v1.EmbeddingService/EncodeQueries',
                request_serializer=embedding__pb2.EncodeRequest.SerializeToString,
                response_deserializer=embedding__pb2.EncodeResponse.FromString,
                _registered_method=True)
        self.EncodeImages = channel.unary_unary(
                '/shikomi.embedding.v1.EmbeddingService/EncodeImages',
                request_serializer=embedding__pb2.ImageEncodeRequest.SerializeToString,
                response_deserializer=embedding__pb2.EncodeResponse.FromString,
                _registered_method=True)
        self.EncodeDocumentsStream = channel.stream_stream(
                '/shikomi.embedding.v1.EmbeddingService/EncodeDocumentsStream',
                request_serializer=embedding__pb2.EncodeRequest.SerializeToString,
                response_deserializer=embedding__pb2.EncodeResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/shikomi.embedding.v1.EmbeddingService/HealthCheck',
                request_serializer=embedding__pb2.HealthRequest.SerializeToString,
                response_deserializer=embedding__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.GetConfig = channel.unary_unary(
                '/shikomi.embedding.v1.EmbeddingService/GetConfig',
                request_serializer=embedding__pb2.ConfigRequest.SerializeToString,
                response_deserializer=embedding__pb2.ConfigResponse.FromString,
                _registered_method=True)


class EmbeddingServiceServicer(object):
    """EmbeddingService provides multi-vector embedding operations.
    Supports both text and image inputs via ColNomic multimodal embeddings.
    Text and image embeddings share the same vector space.
    """

    def EncodeDocuments(self, request, context):
        """Encode documents for storage/indexing.
        Documents are prefixed with the document_prefix from config.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EncodeQueries(self, request, context):
        """Encode queries for search (with query prefix).
        Queries are prefixed with the query_prefix from config.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EncodeImages(self, request, context):
        """Encode images for storage/indexing.
        Uses ColNomic vision encoder - embeddings are in the same
        vector space as text embeddings for cross-modal search.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EncodeDocumentsStream(self, request_iterator, context):
        """Stream encoding for large batches.
        Useful for bulk indexing operations.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check for load balancing.
        Returns current worker status and metrics.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConfig(self, request, context):
        """Get model configuration.
        Returns model name, dimensions, and other settings.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EmbeddingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EncodeDocuments': grpc.unary_unary_rpc_method_handler(
                    servicer.EncodeDocuments,
                    request_deserializer=embedding__pb2.EncodeRequest.FromString,
                    response_serializer=embedding__pb2.EncodeResponse.SerializeToString,
            ),
            'EncodeQueries': grpc.unary_unary_rpc_method_handler(
                    servicer.EncodeQueries,
                    request_deserializer=embedding__pb2.EncodeRequest.FromString,
                    response_serializer=embedding__pb2.EncodeResponse.SerializeToString,
            ),
            'EncodeImages': grpc.unary_unary_rpc_method_handler(
                    servicer.EncodeImages,
                    request_deserializer=embedding__pb2.ImageEncodeRequest.FromString,
                    response_serializer=embedding__pb2.EncodeResponse.SerializeToString,
            ),
            'EncodeDocumentsStream': grpc.stream_stream_rpc_method_handler(
                    servicer.EncodeDocumentsStream,
                    request_deserializer=embedding__pb2.EncodeRequest.FromString,
                    response_serializer=embedding__pb2.EncodeResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=embedding__pb2.HealthRequest.FromString,
                    response_serializer=embedding__pb2.HealthResponse.SerializeToString,
            ),
            'GetConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConfig,
                    request_deserializer=embedding__pb2.ConfigRequest.FromString,
                    response_serializer=embedding__pb2.ConfigResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'shikomi.embedding.v1.EmbeddingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('shikomi.embedding.v1.EmbeddingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EmbeddingService(object):
    """EmbeddingService provides multi-vector embedding operations.
    Supports both text and image inputs via ColNomic multimodal embeddings.
    Text and image embeddings share the same vector space.
    """

    @staticmethod
    def EncodeDocuments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shikomi.embedding.v1.EmbeddingService/EncodeDocuments',
            embedding__pb2.EncodeRequest.SerializeToString,
            embedding__pb2.EncodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EncodeQueries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shikomi.embedding.v1.EmbeddingService/EncodeQueries',
            embedding__pb2.EncodeRequest.SerializeToString,
            embedding__pb2.EncodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EncodeImages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shikomi.embedding.v1.EmbeddingService/EncodeImages',
            embedding__pb2.ImageEncodeRequest.SerializeToString,
            embedding__pb2.EncodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EncodeDocumentsStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/shikomi.embedding.v1.EmbeddingService/EncodeDocumentsStream',
            embedding__pb2.EncodeRequest.SerializeToString,
            embedding__pb2.EncodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shikomi.embedding.v1.EmbeddingService/HealthCheck',
            embedding__pb2.HealthRequest.SerializeToString,
            embedding__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shikomi.embedding.v1.EmbeddingService/GetConfig',
            embedding__pb2.ConfigRequest.SerializeToString,
            embedding__pb2.ConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
